// data.js
const WORD_DATABASE = [
  { word: "여운", emoji: "🎐", hint: "남아 있는 느낌", meaning: "지나간 뒤에도 마음은 머물러요" },
  { word: "고마움", emoji: "🌼", hint: "마음이 숙여지는 순간", meaning: "당연하지 않았음을 아는 마음" },
  { word: "포근", emoji: "🧣", hint: "감싸지는 감각", meaning: "있는 그대로도 안전해요" },
  { word: "숨", emoji: "🌫️", hint: "잠깐의 호흡", meaning: "지금 여기로 돌아오는 신호" },
  { word: "비움", emoji: "🫙", hint: "덜어내는 선택", meaning: "가벼워질 자리를 만드는 일" },
  { word: "머묾", emoji: "🪑", hint: "잠시 앉아 있음", meaning: "서두르지 않아도 괜찮아요" },
  { word: "차분", emoji: "🪶", hint: "가라앉은 상태", meaning: "마음이 제 속도로 돌아와요" },
  { word: "다짐", emoji: "📜", hint: "조용한 약속", meaning: "크지 않아도 진심이면 돼요" },
  { word: "수용", emoji: "🫶", hint: "있는 그대로 안기", meaning: "바꾸지 않아도 괜찮은 날" },
  { word: "여기", emoji: "📍", hint: "지금의 자리", meaning: "도망치지 않아도 되는 순간" },

  { word: "잔잔", emoji: "🌾", hint: "파도 없는 마음", meaning: "아무 일 없어도 좋은 하루" },
  { word: "회복", emoji: "🩹", hint: "다시 이어짐", meaning: "천천히 괜찮아지고 있어요" },
  { word: "기다림", emoji: "⏳", hint: "서두르지 않음", meaning: "때가 오면 자연히 와요" },
  { word: "마주", emoji: "🪞", hint: "스스로를 봄", meaning: "외면하지 않은 용기" },
  { word: "연결", emoji: "🧵", hint: "이어지는 마음", meaning: "혼자가 아니라는 감각" },
  { word: "안도", emoji: "🫁", hint: "숨이 내려앉음", meaning: "긴장이 풀리는 순간" },
  { word: "배려", emoji: "🌱", hint: "조심스러운 마음", meaning: "상대보다 먼저 나에게도" },
  { word: "고른", emoji: "⚖️", hint: "치우치지 않음", meaning: "지나치지 않은 균형" },
  { word: "맑음", emoji: "💧", hint: "투명한 상태", meaning: "생각이 정리되는 시간" },
  { word: "여지", emoji: "🚪", hint: "열어둔 틈", meaning: "가능성을 남겨두는 선택" },

  { word: "견딤", emoji: "🪨", hint: "버텨온 시간", meaning: "여기까지 온 것도 충분해요" },
  { word: "보듬", emoji: "🧸", hint: "감싸 안음", meaning: "상처 난 마음도 쉬어가요" },
  { word: "순간", emoji: "📸", hint: "짧은 지금", meaning: "지금도 하나의 완성" },
  { word: "흐름", emoji: "🌊", hint: "자연스러움", meaning: "거스르지 않아도 괜찮아요" },
  { word: "온전", emoji: "🟢", hint: "나 그대로", meaning: "고칠 필요 없는 상태" },
  { word: "여백", emoji: "📄", hint: "비어 있는 공간", meaning: "숨 쉴 자리를 남겨요" },
  { word: "자람", emoji: "🌿", hint: "조용한 성장", meaning: "눈에 안 보여도 자라고 있어요" },
  { word: "돌봄", emoji: "🫖", hint: "스스로를 챙김", meaning: "오늘의 나를 먼저" },
  { word: "정돈", emoji: "🧺", hint: "마음의 정리", meaning: "어지러워도 괜찮아요" },
  { word: "한숨", emoji: "💭", hint: "내려놓는 숨", meaning: "내쉬는 것만으로도 충분해요" },

  // ===== 3글자 단어 추가 =====
  { word: "고요함", emoji: "🌙", hint: "소리 없는 평온", meaning: "가만히 있어도 평화로워요" },
  { word: "따뜻함", emoji: "☀️", hint: "온기 있는 마음", meaning: "차갑지 않아도 괜찮아요" },
  { word: "편안함", emoji: "🛏️", hint: "긴장이 풀린 상태", meaning: "꾸밀 필요 없는 자리" },
  { word: "가벼움", emoji: "🪶", hint: "무겁지 않은 감각", meaning: "놓아버린 후의 홀가분함" },
  { word: "다정함", emoji: "🤝", hint: "따뜻한 손길", meaning: "작은 관심도 큰 위로가 돼요" },
  { word: "소중함", emoji: "💎", hint: "귀한 것", meaning: "당신이 있어서 감사해요" },
  { word: "넉넉함", emoji: "🏡", hint: "충분한 공간", meaning: "자리가 있으니 와도 괜찮아요" },
  { word: "부드러움", emoji: "☁️", hint: "부드러운 감촉", meaning: "날카롭지 않은 말 한마디" },
  { word: "깊이감", emoji: "🌊", hint: "깊은 수심", meaning: "표면 아래 있는 진심" },
  { word: "희망찬", emoji: "🌅", hint: "밝은 앞날", meaning: "내일도 할 수 있을 것 같아요" },

  // ===== 4글자 단어 추가 =====
  { word: "아무도모르게", emoji: "🤫", hint: "조용하게 하는 선의", meaning: "보상 없이 주는 마음" },
  { word: "천천히", emoji: "🐢", hint: "서두르지 말기", meaning: "급할 필요 없어요" },
  { word: "그대로가", emoji: "✨", hint: "있는 그대로의 가치", meaning: "바꿀 필요 없는 당신" },
  { word: "살고싶은", emoji: "🌟", hint: "원하는 삶의 방식", meaning: "자기 속도가 제일 좋아요" },
  { word: "놓아주기", emoji: "🕊️", hint: "손을 펼침", meaning: "붙들지 않은 사랑도 있어요" },
  { word: "알아주기", emoji: "👁️", hint: "내 맘 알아주기", meaning: "말 없이도 이해해줘요" },
  { word: "감사하는", emoji: "🙏", hint: "고마워하는 마음", meaning: "당신이 있어 좋아요" },
  { word: "이어가기", emoji: "🔗", hint: "계속 연결되기", meaning: "끝나지 않는 마음" }
];